controller_manager:
  ros__parameters:
    update_rate: 100

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["robot_left_wheel_joint"]
    right_wheel_names: ["robot_right_wheel_joint"]
    wheel_separation: 0.5032 # From wheel_offset_y * 2 in rb_theron_base.urdf.xacro
    wheel_radius: 0.0762 # From rubber_wheel_150.urdf.xacro
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: robot_base_footprint
    use_stamped_vel: true
